### ISSUE TITLE
Breakfast recipe is missing

### ISSUE THREAD

**Issue by user-je** [IntroToCode/CodeMates1_Fall23#1]
## 💬 Discussion topic

Breakfast recipe information is missing - we need to fill in all the recipe fields. See fields and suggested team mate assignments in "Details" section below.

## ❗ Potential issues

Fields for the recipe are blank because they have not been populated yet.

## 👥 People to consult

@user-je , Xan

## 📃 Details
SUGGESTIONED TASKS:

Replace with recipe name - **Juli**
Servings: - **Juli**
Time to prepare: - **Juli**
Ingredients: - **Juli**
Equipment needed: - **Juli**
Steps for preparation: - **Juli**
Notes: - **Xan**
Codemates - **Xan**

**Comment by woodmeistergeneral** [comment]
Okay this makes sense to me let me take a look

**Comment by user-je** [comment]
Everyone completed their tasks. LGTM
