### ISSUE TITLE
Dinner recipe is missing

### ISSUE THREAD

**Issue by user-je** [IntroToCode/CodeMates1_Fall23#2]
## 💬 Discussion topic

Dinner recipe information is missing - we need to fill in all the recipe fields. See fields and suggested team mate assignments in "Details" section below.

## ❗ Potential issues

Fields for the recipe are blank because they have not been populated yet.

## 👥 People to consult

@ismaildesouki, @nabeelmuhammad 

## 📃 Details
SUGGESTIONED TASKS:

Replace with recipe name - **Nabeel**
Servings: - **Nabeel**
Time to prepare: - **Ismail**
Ingredients: - **Ismail**
Equipment needed: - **Ismail**
Steps for preparation: - **Ismail**
Notes: - **Nabeel**
Codemates - **Nabeel**

**Comment by ismaildesouki** [comment]
Steak dinner looks great now!

**Comment by user-je** [comment]
Everyone completed their tasks. LGTM
